### ISSUE TITLE
single search ux

### ISSUE THREAD

**Issue by dufoli** [dufoli/Salesforce-Inspector-Advanced#132]
context:
- shortcut is too long because it need click on tab then keyboard
- need to open menu to access to shortcut module with "s" keyboard shortcut
- only flow, profile and pset is supported => all config must be accessible too

**TODO**
- [ ] merge object, shortcut and user tab and org
- [ ] add org in search + all setup page
- [ ] have a single search bar
- [ ] search in user from current object by username and email (sosl)
- [ ] use ":" or "@" for shortcut in search bar a bit like vscode sublimText
