### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by dufoli** [dufoli/Salesforce-Inspector-Advanced#5]
Roadmap to clarify and create sub ticket:

1.29:
- [ ] #152
- [ ] #151
- [ ] #27
- [ ] #61
- [ ] #19 
- [ ] #144
- [ ] #22
- [ ] #134
- [ ] #136
- [ ] #94

1.30:
- [ ] #127 
- [ ] #132
- [ ] #13
- [ ] #116
- [ ] #137 
- [ ] #128 
- [ ] #129 
- [ ] #25
- [ ] #74
- [ ] #114
- [ ] #72
- [ ] #83
- [ ] #21
- [ ] #70
- [ ] #57
- [ ] #109

Previous releases:
- [x] sosl support
- [x] export guess for object and externalid
- [x] apex runner for batch and queue
- [x] download apex log button
- [x] log viewer with search
- [x] log analyzer : plain text, org limits, stack trace, apex cpu limits, profiler)
- [x] fix intellisens on subquery
- [x] respect order of column of query instead of object return
- [x] publish on stores

1.24:
- [x] increase height of popup window
- [x] format soql sosl
- [x] support comment in soql
- [x] maj chrome store link to documentation
- [x] #20
- [x] #28
- [x] #23
- [x] #26 
- [x] #31
- [x] #36 
- [x] #33 
- [x] #40 

1.25
- [x] #11
- [x] #45 
- [x] #43
- [x] #47
- [x] #55
- [x] #42
- [x] #63
- [x] #58
- [x] #59
- [x] #60
- [x] #24 

1.26:
- [x] #71
- [x] #78
- [x] #30 
- [x] #62
- [x] #75
- [x] #41
- [x] #73
- [x] #85
- [x] #50
- [x] #86
- [x] #91
- [x] #80
- [x] #77
- [x] #90
- [x] #89 
- [x] #103
- [x] #69

1.27:
- [x] #48
- [x] #108 
- [x] #15 register app to log event emission
- [x] #37
- [x] #105
- [x] #106
- [x] #117
- [x] fix firefox build
- [x] push event 
- [x] #115 
- [x] #97

1.28:
- [x] #135
- [x] #130
- [x] #84
- [x] #139
- [x] #126 
- [x] #138 
- [x] #125 
- [x] #140
- [x] #141
- [x] #123

**Comment by dufoli** [comment]
let s use roadmap
